/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:f9fd7e9f-a9b1-4669-8d3e-d5dc906afd52",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_4GxVQiPbN",
    "aws_user_pools_web_client_id": "35aqltngqvntdndckc7q6ltpfu",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://eqmi2rwfubag5kb7x7kzqwerya.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
