name: Server Deploy
on:
  push: # master Branch에서 push 이벤트가 일어났을 때만 실행
    paths:
      - server/**
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo su
            cd store-10/store-10
            sudo git stash
            sudo git stash drop
            sudo git pull
            cd server
            sudo npm install
